#!/bin/bash
#
# Set our bash prompt according to the branch/status of the current git
# repository.
#
# Forked from http://gist.github.com/31967

# HUB alias
if hash hub 2>&-; then
  alias git=hub
fi

        RED="\[\033[0;31m\]"
     YELLOW="\[\033[0;33m\]"
      GREEN="\[\033[0;32m\]"
       BLUE="\[\033[0;34m\]"
  LIGHT_RED="\[\033[1;31m\]"
LIGHT_GREEN="\[\033[1;32m\]"
      WHITE="\[\033[1;37m\]"
 LIGHT_GRAY="\[\033[0;37m\]"
 COLOR_NONE="\[\e[0m\]"

function is_git_repository()
{
  git branch > /dev/null 2>&1
}

function parse_git_branch()
{
  # Only display git info if we're inside a git repository.
  is_git_repository || return 1

  # Capture the output of the "git status" command.
  git_status="$(git status 2> /dev/null)"

  # Set color based on clean/staged/dirty.
  if [[ ${git_status} =~ "working directory clean" ]]; then
    state_color="${GREEN}"
  elif [[ ${git_status} =~ "Changes to be committed" ]]; then
    state_color="${YELLOW}"
    state_icon="⚡"
  else
    state_color="${RED}"
    state_icon="⚡"
  fi

  # Set arrow icon based on status against remote.
  remote_pattern="# Your branch is (ahead|behind)"
  if [[ ${git_status} =~ ${remote_pattern} ]]; then
    if [[ ${BASH_REMATCH[1]} == "ahead" ]]; then
      remote="↑"
    else
      remote="↓"
    fi
  fi
  diverge_pattern="# Your branch and (.*) have diverged"
  if [[ ${git_status} =~ ${diverge_pattern} ]]; then
    remote="↕"
  fi

  # Get the name of the branch.
  branch_pattern="^# On branch ([^${IFS}]*)"
  if [[ ${git_status} =~ ${branch_pattern} ]]; then
    branch=${BASH_REMATCH[1]}
  fi

  # Display the prompt.
  echo "${state_color}(${branch})${state_icon}${remote}${COLOR_NONE} "
}

function prompt_symbol()
{
  # Set color of dollar prompt based on return value of previous command.
  if test $1 -eq 0
  then
      echo "\$"
  else
      echo "${RED}\$${COLOR_NONE}"
  fi
}

function parse_git_dir()
{
  dir_pattern="Development\/clients/([^\/]+\/[^\/]+)(\/.+)?"
  if [[ $(pwd) =~ ${dir_pattern} ]]
  then
    if [[ ${BASH_REMATCH[2]} != "" ]]
    then
      dir="${BASH_REMATCH[1]} \W"
    else
      dir="${BASH_REMATCH[1]} ~"
    fi
  else
    dir="\W"
  fi
  echo "$dir"
}

function prompt_func()
{
  last_return_value=$?
  # PS1="\u@\h \W $(parse_git_branch)$(prompt_symbol $last_return_value) "
  PS1="\u $(parse_git_dir) $(parse_git_branch)$(prompt_symbol $last_return_value) "
}

PROMPT_COMMAND=prompt_func
