brew tap homebrew/versions
brew tap codeclimate/formulae
brew tap thoughtbot/formulae
brew install cmake
brew install codeclimate
brew install docker-compose
brew install git
brew install lastpass-cli
brew install nvm
brew install postgresql94
brew install rbenv
brew install rcm
brew install redis
brew install ruby-build
brew install tmux
brew install vim
