#!/bin/sh

# Install rbenv plugins
if command -v rbenv >/dev/null 2>&1; then
  mkdir -p "$(rbenv root)/plugins"
  if [ ! -e "$(rbenv root)/plugins/rbenv-aliases" ]; then
    git clone https://github.com/tpope/rbenv-aliases.git \
        "$(rbenv root)/plugins/rbenv-aliases"
    rbenv alias --auto
  fi

  if [ ! -e "$(rbenv root)/plugins/rbenv-default-gems" ]; then
    git clone https://github.com/rbenv/rbenv-default-gems.git \
        "$(rbenv root)/plugins/rbenv-default-gems"
  fi
fi

# Ensure zsh directory exists
mkdir -p $HOME/.zsh

sudo locale-gen en_US.UTF-8