#!/bin/env zsh

function project_name() {
  name=$(pwd | sed -n 's:\(^.*/[^/]*/[^/]*\).*$:\1:p' | tr -d '.' | awk -F/ '{print $(NF-1) "/" $(NF)}' | tr '/' '-')
  if [ -z "$name" ]; then
    name='default'
  fi

  echo "$name"
}

function dev() {
  working_directory=$1
  cd $working_directory
}

function dotfiles() {
  dev ~/.dotfiles
}
