#!/bin/env zsh

if command -v keychain >/dev/null 2>&1; then
  #/usr/bin/keychain -q $HOME/.ssh/id_rsa $HOME/.ssh/id_ed25519
  /usr/bin/keychain -q $HOME/.ssh/id_ed25519
  source $HOME/.keychain/$HOST-sh
fi
