#!/bin/env zsh

function _docker_backend_service() {
  _compose_services | grep -E '(dev|backend)' | tr '\n' ' ' | sed 's/ $//'
}

#
# Drupal related commands, to be run inside the backend container.
#
function drush() {
  docker compose exec "$(_docker_backend_service)" ./vendor/bin/drush "$@"
}

function docker-as-drupal() {
  local service=$(_docker_backend_service)

  # behat and phpunit belong to the test environment, everything else runs
  # against the dev backend.
  if (( $# )) && [[ "$1" == "behat" || "$1" == "phpunit" ]]; then
    service="test"
  fi

  docker compose exec "$service" docker-as-drupal "$@"
}

#
# WordPress related commands, to be run inside the backend container.
#
function wp() {
  docker compose exec "$(_docker_backend_service)" wp "$@"
}

function docker-as-wordpress() {
  docker compose exec "$(_docker_backend_service)" docker-as-wordpress "$@"
}

#
# PHP tools, to be run inside the project directory.
#
function _php_tool() {
  local name=$1
  shift

  if [[ ! -d "tools/$name" ]]; then
    print -u2 "./tools/$name does not exist"
    return 1
  fi

  ( cd "tools/$name" && composer install ) || return

  "./tools/$name/vendor/bin/$name" "$@"
}

function _vendor_bin() {
  local name=$1
  shift

  if [[ ! -x "./vendor/bin/$name" ]]; then
    print -u2 "./vendor/bin/$name does not exist"
    return 1
  fi

  "./vendor/bin/$name" "$@"
}

function php-cs-fixer() {
  if (( $# == 0 )) || [[ $# -eq 1 && "$1" == "check" ]]; then
    _php_tool php-cs-fixer check --config=.php-cs-fixer.php --using-cache=no
  elif [[ $# -eq 1 && "$1" == "fix" ]]; then
    _php_tool php-cs-fixer fix --config=.php-cs-fixer.php --using-cache=no
  else
    _php_tool php-cs-fixer "$@"
  fi
}

function psalm() {
  if (( $# == 0 )); then
    _php_tool psalm --config=psalm.xml --no-cache
  elif [[ $# -eq 1 && "$1" == "--alter" ]]; then
    _php_tool psalm --config=psalm.xml --no-cache --alter --issues=all
  else
    _php_tool psalm "$@"
  fi
}

function phpcs() {
  _vendor_bin phpcs "$@"
}

function phpcbf() {
  _vendor_bin phpcbf "$@"
}
